### ISSUE TITLE
[Front][송금] 간편 비밀번호 구현 순서 미룸 관련

### ISSUE THREAD

**Issue by sunJ0120** [kookmin-sw/capstone-2024-45#16]
우선 간편 비밀번호의 경우...교수님께서 말씀하셨듯이 당장 "이게 필요한가? 어떤 기능을 위해서?"를 논의해봐야 할 것 같습니다

또한 이 기능이 주요 기능이 아니기에(특히 지금은 로그인이랑 송금 예외사항을 먼저 다듬어야 할 것 같습니다.)개발 순서를 후순위로 미뤄도 될까 의견을 구하고 싶습니다.(무엇보다 제가 지금 qr 부분을 싹 다듬어야 할 것 같아서 이번주 안에 간편 비밀번호 구현을 다 못마칠 것 같습니다...ㅠ)

**Comment by ytjdud** [comment]
간편비밀번호 구현이라는게 앱 접근+송금. 두 가지 케이스에 대해 모두 적용하는 건가요?
저는 어느 케이스이든 당장 구현해야할 사항은 아니라고 생각합니다. 송금 프로세스가 되냐/안되냐가 더 중요하니..

**Comment by sunJ0120** [comment]
넵넵 원래는 앱 로그인 + 송금 시 적용하려고 했었는데, 화요 회의 과정에서 필요성에 대한 의문도 나왔었고
 저도 당장 이것보단 송금 프로세스의 문제점을 다듬는게 우선이라고 생각합니다..!
