### ISSUE TITLE
[Front][송금] QR 송금 프론트 시퀀스 다이어그램 정리

### ISSUE THREAD

**Issue by sunJ0120** [kookmin-sw/capstone-2024-45#46]
![시퀀스 다이어그램_qr송금](https://github.com/kookmin-sw/capstone-2024-45/assets/134828984/fa58cce0-9aa2-439d-b337-e3b021e7cc39)

**Comment by ytjdud** [comment]
QR 생성/스캔 시 HMAC 적용된 시퀀스.

![image](https://github.com/kookmin-sw/capstone-2024-45/assets/102743371/c91b5a13-e527-49d1-b1f0-bf09f14b4567)
